---
- name: Upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: "yes"

- name: Install tools
  become: yes
  apt:
    state: present
    autoclean: yes
    autoremove: yes
    name:
      - curl
      - htop
      - git
      - zsh
      - software-properties-common
      - 